apiVersion: v1
kind: Service
metadata:
  name: cars_app
spec:
  selector:
    app: cars_app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars_app
spec:
  selector:
    matchLabels:
      app: cars_app
  replicas: 5
  template:
    metadata:
      labels:
        app: cars_app
    spec:
      containers:
      - name: cars_app
        image: docker.io/19179422/cars_app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000