apiVersion: v1
kind: Service
metadata:
  name: cars-service
spec:
  selector:
    app: cars-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-app
spec:
  selector:
    matchLabels:
      app: cars-app
  replicas: 5 
  template:
    metadata:
      labels:
        app: cars-app
    spec:
      containers:
      - name: cars-app
        image: docker.io/19179422/cars_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        command: ["/bin/sh", "-ec", "sleep 1000"]