version: "3.9"

services:
    cars-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            MONGO_CLIENT: "mongodb+srv://19179422:soft7011@cluster0.whl83.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
            DATABASE_URL: "postgresql://irfthlqtvpqjek:35496e5703ba65a8c9fe2a2075e9d4395a7aa6e29ccc710c8f3966ea4eea7ba5@ec2-99-81-16-126.eu-west-1.compute.amazonaws.com:5432/d6iso2pc6h1bkj"
        image: cars-app
        ports:
            - 5000:5000
